[Interface]
PrivateKey = IBp8W9lfrQMUZRBLOI9VSkbT2fT0txAYhCuSYeScvX0=
Address = 10.8.0.8/32
DNS = 1.1.1.1

[Peer]
PublicKey = rSggM5eZLjqnewe4jEoHTbrAK+0BOkLfFnmRBG7c7Fs=
Endpoint = 129.146.227.29:51820
AllowedIPs = 10.8.0.0/24
PersistentKeepalive = 25
